class SchoolService {
  static const List<String> _punjabSchools = [
    'Government Model Senior Secondary School, Amritsar',
    'Delhi Public School, Amritsar',
    'Spring Dale Senior School, Amritsar',
    'Sacred Heart Convent School, Amritsar',
    'B.C.M. School, Amritsar',
    'D.A.V. Public School, Amritsar',
    'St. Francis School, Amritsar',
    'Guru Nanak Dev Public School, Amritsar',
    'Government Model Senior Secondary School, Ludhiana',
    'Delhi Public School, Ludhiana',
    'B.C.M. School, Ludhiana',
    'D.A.V. Public School, Ludhiana',
    'Spring Dale Senior School, Ludhiana',
    'Sacred Heart Convent School, Ludhiana',
    'St. Francis School, Ludhiana',
    'Guru Nanak Dev Public School, Ludhiana',
    'Government Model Senior Secondary School, Jalandhar',
    'Delhi Public School, Jalandhar',
    'B.C.M. School, Jalandhar',
    'D.A.V. Public School, Jalandhar',
    'Spring Dale Senior School, Jalandhar',
    'Sacred Heart Convent School, Jalandhar',
    'St. Francis School, Jalandhar',
    'Guru Nanak Dev Public School, Jalandhar',
    'Government Model Senior Secondary School, Patiala',
    'Delhi Public School, Patiala',
    'B.C.M. School, Patiala',
    'D.A.V. Public School, Patiala',
    'Spring Dale Senior School, Patiala',
    'Sacred Heart Convent School, Patiala',
    'St. Francis School, Patiala',
    'Guru Nanak Dev Public School, Patiala',
    'Government Model Senior Secondary School, Bathinda',
    'Delhi Public School, Bathinda',
    'B.C.M. School, Bathinda',
    'D.A.V. Public School, Bathinda',
    'Spring Dale Senior School, Bathinda',
    'Sacred Heart Convent School, Bathinda',
    'St. Francis School, Bathinda',
    'Guru Nanak Dev Public School, Bathinda',
    'Government Model Senior Secondary School, Mohali',
    'Delhi Public School, Mohali',
    'B.C.M. School, Mohali',
    'D.A.V. Public School, Mohali',
    'Spring Dale Senior School, Mohali',
    'Sacred Heart Convent School, Mohali',
    'St. Francis School, Mohali',
    'Guru Nanak Dev Public School, Mohali',
    'Government Model Senior Secondary School, Ferozepur',
    'Delhi Public School, Ferozepur',
    'B.C.M. School, Ferozepur',
    'D.A.V. Public School, Ferozepur',
    'Spring Dale Senior School, Ferozepur',
    'Sacred Heart Convent School, Ferozepur',
    'St. Francis School, Ferozepur',
    'Guru Nanak Dev Public School, Ferozepur',
    'Government Model Senior Secondary School, Gurdaspur',
    'Delhi Public School, Gurdaspur',
    'B.C.M. School, Gurdaspur',
    'D.A.V. Public School, Gurdaspur',
    'Spring Dale Senior School, Gurdaspur',
    'Sacred Heart Convent School, Gurdaspur',
    'St. Francis School, Gurdaspur',
    'Guru Nanak Dev Public School, Gurdaspur',
    'Government Model Senior Secondary School, Hoshiarpur',
    'Delhi Public School, Hoshiarpur',
    'B.C.M. School, Hoshiarpur',
    'D.A.V. Public School, Hoshiarpur',
    'Spring Dale Senior School, Hoshiarpur',
    'Sacred Heart Convent School, Hoshiarpur',
    'St. Francis School, Hoshiarpur',
    'Guru Nanak Dev Public School, Hoshiarpur',
    'Government Model Senior Secondary School, Kapurthala',
    'Delhi Public School, Kapurthala',
    'B.C.M. School, Kapurthala',
    'D.A.V. Public School, Kapurthala',
    'Spring Dale Senior School, Kapurthala',
    'Sacred Heart Convent School, Kapurthala',
    'St. Francis School, Kapurthala',
    'Guru Nanak Dev Public School, Kapurthala',
    'Government Model Senior Secondary School, Moga',
    'Delhi Public School, Moga',
    'B.C.M. School, Moga',
    'D.A.V. Public School, Moga',
    'Spring Dale Senior School, Moga',
    'Sacred Heart Convent School, Moga',
    'St. Francis School, Moga',
    'Guru Nanak Dev Public School, Moga',
    'Government Model Senior Secondary School, Muktsar',
    'Delhi Public School, Muktsar',
    'B.C.M. School, Muktsar',
    'D.A.V. Public School, Muktsar',
    'Spring Dale Senior School, Muktsar',
    'Sacred Heart Convent School, Muktsar',
    'St. Francis School, Muktsar',
    'Guru Nanak Dev Public School, Muktsar',
    'Government Model Senior Secondary School, Nawanshahr',
    'Delhi Public School, Nawanshahr',
    'B.C.M. School, Nawanshahr',
    'D.A.V. Public School, Nawanshahr',
    'Spring Dale Senior School, Nawanshahr',
    'Sacred Heart Convent School, Nawanshahr',
    'St. Francis School, Nawanshahr',
    'Guru Nanak Dev Public School, Nawanshahr',
    'Government Model Senior Secondary School, Rupnagar',
    'Delhi Public School, Rupnagar',
    'B.C.M. School, Rupnagar',
    'D.A.V. Public School, Rupnagar',
    'Spring Dale Senior School, Rupnagar',
    'Sacred Heart Convent School, Rupnagar',
    'St. Francis School, Rupnagar',
    'Guru Nanak Dev Public School, Rupnagar',
    'Government Model Senior Secondary School, Sangrur',
    'Delhi Public School, Sangrur',
    'B.C.M. School, Sangrur',
    'D.A.V. Public School, Sangrur',
    'Spring Dale Senior School, Sangrur',
    'Sacred Heart Convent School, Sangrur',
    'St. Francis School, Sangrur',
    'Guru Nanak Dev Public School, Sangrur',
    'Government Model Senior Secondary School, Tarn Taran',
    'Delhi Public School, Tarn Taran',
    'B.C.M. School, Tarn Taran',
    'D.A.V. Public School, Tarn Taran',
    'Spring Dale Senior School, Tarn Taran',
    'Sacred Heart Convent School, Tarn Taran',
    'St. Francis School, Tarn Taran',
    'Guru Nanak Dev Public School, Tarn Taran',
  ];

  static List<String> getAllSchools() {
    return List.from(_punjabSchools);
  }

  static List<String> searchSchools(String query) {
    if (query.isEmpty) return getAllSchools();
    
    return _punjabSchools
        .where((school) => school.toLowerCase().contains(query.toLowerCase()))
        .toList();
  }

  static String getSchoolEmail(String schoolName) {
    // Generate a mock email for the school
    final schoolKey = schoolName
        .toLowerCase()
        .replaceAll(' ', '_')
        .replaceAll(',', '')
        .replaceAll('.', '');
    return 'admin@$schoolKey.edu.in';
  }
}
